In [1]:
pip install decision-tree-id3

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.7/154.7 kB 3.3 MB/s eta 0:00:00
  Created wheel for decision-tree-id3: filename=decision_tree_id3-0.1.2-py3-none-any.whl size=15940 sha256=5299b8f07f78c736754971a1c43be5a381baf3312c22dcf5de79877f797ab653
  Stored in directory: /root/.cache/pip/wheels/8c/cd/e4/e2acaaf5eea93ac56371528d7aee422950510b631443217c77
Successfully built decision-tree-id3


In [ ]:
pip install pandas

In [ ]:
pip install numpy

In [ ]:
pip install scikit-learn

In [ ]:
pip install six

Apos intalar os Arquivos nescessário, e preciso importar as funções que seram nescessária na execução no código

**six:** Biblioteca usada para gerar uma compartibilidades dentre as varias versões do python, assim um comando de uma versão python antigo funcionária numa mais nova;

**pandas:** Possui funções que são essencias na analise e manipulação de dados, planilhas eletrônicas.

**numpy:** Possui funções que auxilam na execução de calculos númericos, usando em calculos de array(matrizes) multidimensionais;

**scikit_learn**: Contem bibliotexa de machine learning, inclui algoritmo de classificação, regreção e agrupamento.

**decision_tree-id3**: Usado para definir a intropia, atravez do algoritmo id3 contindo na biblioteca


In [ ]:
#importa as funções que seram usadas no códigos, todas as elas referenciaas as
#bibliotecas instala no campo anterior
import six
import sys
sys.modules['sklearn.externals.six'] = six
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from id3 import Id3Estimator
from id3 import export_graphviz
import numpy as np

In [ ]:
#Faz leitura do Arquivo com as informações para montar a árvore, caso seja um
#arquivo em csv, coloca-se o 'sep = ;' para delemitar os campos, e conseguir
#separar de forma correta nos proximos passos
arquivo = pd.read_csv('dadosIA.csv')

Precisa fazer agora a serparação dos valores;

-- Na primeiro etapa e precisa definir os previsores, que são as variaveis observaveis do projeto, que também são os atributos.

-- Na Segunda etapa separa quem será a classe, que um atributos que dependentes de outros para definir seu valor.

-- Na Terceira seleciona os nomes dos atributos, ou nomes dos arquivos.

In [ ]:
# Seleciona atravez do iloc, todas as linhas com o (":"),e as colunas que começa no 0 e vai ate a coluna 9.
# O ".values" indica que esta pegando o valor dessa coluna
previsores = arquivo.iloc[:,0:9].values
print(previsores)

#Seleciona, todas as linhas, e apenas a coluna que contem a classe
classe = arquivo.iloc[:,9].values
print(classe)

#Seleciona, todas as linhas e colunas da tabela, porem so irá pegar os nome que
#corresponde a cada colunas
colunas = np.asarray(arquivo.columns[0:9])
print(colunas);

Apois isso será feita uma conversão das váriaveis, na planilhas ela consta valores categoricas, valores que definiam um atributos, para que possa fazer os calculos subsequentes e preciso transforma-los em números. Comando usado: labelencoder.fit_transform

In [ ]:
#Transforma váriaveis categoricas em númericas
labelencoder = LabelEncoder()
previsores[:,0] = labelencoder.fit_transform(previsores[:,0])
previsores[:,1] = labelencoder.fit_transform(previsores[:,1])
previsores[:,2] = labelencoder.fit_transform(previsores[:,2])
previsores[:,3] = labelencoder.fit_transform(previsores[:,3])
previsores[:,4] = labelencoder.fit_transform(previsores[:,4])
previsores[:,5] = labelencoder.fit_transform(previsores[:,5])
previsores[:,6] = labelencoder.fit_transform(previsores[:,6])
previsores[:,7] = labelencoder.fit_transform(previsores[:,7])
previsores[:,8] = labelencoder.fit_transform(previsores[:,8])
print("Depois da transformação:")
print(previsores)

Depois da transformação:
[[2 2 2 ... 2 1 1]
 [2 2 2 ... 1 2 1]
 [2 2 2 ... 1 1 2]
 ...
 [1 2 1 ... 2 1 2]
 [1 2 1 ... 2 1 2]
 [1 1 2 ... 1 2 2]]


Parte Final do código, Nessa parte será feito o cálculo do estimator,usando o argoritmo id3, que se encontra na biblioteca decision-tree-id3;

Nesse passo o estimator ira receber o construtor da classe Estimator, tornando então o estimator como uma intancia dessa classe contendo todos os atributos

função .fit, ira criar a arvore de decison basendo nos valores da amostra X (representa os provisores, as variáveis independentes) e seus correspondentes em y (representa os valores da classe).

Nessa função e utilizado o algortimo ID3, em que calcula para cada atributo seu valor de intropia, e seguinda estibula o ganho de informação baseado no atributo de maior intropia.

Em seguida e guardado na variavel um arquivo contendo o código para mostrar a arvore num interface grafica.
estimator.tree: E uma instancia do estimator cpara criar a arvore.


In [ ]:
#Treina a árvore e exporta o resultado
#varivel estimator ira receber o retorno da função Id3Estimator
estimator = Id3Estimator()

#Criar a arvore decisão, como base no ganho de informação estipulada anteriormente
estimator.fit(previsores, classe)
t = export_graphviz(estimator.tree_, 'dadosIA.dot', colunas)

In [ ]:
print(previsores)
print(classe)

#Para ver a imagem da árvore copia o texto do arquivo neste site:
#https://dreampuf.github.io/GraphvizOnline/